name: 'Tests: node.js'

on: [pull_request, push]

permissions:
  contents: read

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.set-matrix.outputs.requireds }}
      minors: ${{ steps.set-matrix.outputs.optionals }}
    steps:
      - uses: ljharb/actions/node/matrix@main
        id: set-matrix
        with:
          versionsAsRoot: true
          type: majors
          preset: '>= 4' # fixme: `npm run react` fails in node 0.8; babel-register for tests fails < node 4

  latest:
    needs: [matrix]
    name: 'majors'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(needs.matrix.outputs.latest) }}
        react:
          - 16
          - 15
          - 15.4
          - 0.14
          - 0.13

    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
          skip-ls-check: true
      - run: npm run react
        name: 'install react ${{ matrix.react }}'
        env:
          REACT: ${{ matrix.react }}
      - run: npm run clean:coverage
      - run: ./node_modules/.bin/nyc --show-process-tree npm run --silent tests-only
      - uses: codecov/codecov-action@v3.1.5

  node:
    name: 'node'
    needs: [latest]
    runs-on: ubuntu-latest
    steps:
      - run: true
